version: '3'

services:
   
   db:
     image: ucp.lab.hoplasoftware.fr:443/sasnoun/postgres:V.9.6.1.3  

   web:
     image: ucp.lab.hoplasoftware.fr:443/sasnoun/djangoforpostgres:V4
     command: bash -c "python /codes/manage.py migrate && python /codes/manage.py runserver 0.0.0.0:8000"
     ports:
       - "82:8000"
     depends_on:
       - "db"
     links:
      - db
     environment:
       - django-project-name=testdjango
       - django-project-name=docker
       - user-postgres=docker
       - password-postgres=docker
       - host-postgres=db
       - port-postgres=5432

 


